In [105]:
import numpy as np

# Given the following configration of NN

In [106]:
W = np.array([[0.01,-0.05, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0, -0.45, -0.2, 0.03]])

x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-2.85  0.86  0.28]
Hinge loss 1.58
[ 1.81109075  0.19985822  0.45174902]
Cross entorp loss 0.451749024431


# Remove W23

In [107]:
W = np.array([[0.01,-0.05, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0, -0.45, -0.2, 0]])


x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-2.85  0.86 -1.4 ]
Hinge loss 3.26
[ 1.6638603   0.05262778  1.03413331]
Cross entorp loss 1.03413330552


# The model after we prune one weight W20

In [108]:
W = np.array([[0.01,-0.05, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0, -0.45, -0.2, 0.03]])


x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-2.85  0.86  0.28]
Hinge loss 1.58
[ 1.81109075  0.19985822  0.45174902]
Cross entorp loss 0.451749024431


# Pruning another weight w11

In [109]:
W = np.array([[0.01,-0.05, 0.1, 0.05],
            [0.7,0,0.05,0.16],
            [0.1, -0.45, -0.2, 0.03]])


x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-2.85 -3.54 -1.22]
Hinge loss 0
[ 0.81990246  1.11956565  0.11200246]
Cross entorp loss 0.112002455795


# Pruning another weight w01

In [110]:
W = np.array([[0.01,0, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0.1, -0.45, -0.2, 0.03]])


x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-1.75  0.86 -1.22]
Hinge loss 3.55
[ 1.21213386  0.07862527  0.98195779]
Cross entorp loss 0.981957789334


# Pruning another weight w21

In [111]:
W = np.array([[0.01,-0.05, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0, 0, -0.2, 0.03]])

x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[ -2.85   0.86  10.18]
Hinge loss 0
[  5.65889697e+00   4.04766444e+00   3.98696331e-05]
Cross entorp loss 3.98696331418e-05


# Pruning another weight w00

In [116]:
W = np.array([[0,-0.05, 0.1, 0.05],
            [0.7,0.2,0.05,0.16],
            [0, -0.45, -0.2, 0.03]])

x = np.array([-15,22, -44, 56])
b = np.array([0, 0.2, -0.3])

o = W.dot(x)+b
print(o)
# Hinge loss (SVM)
L_h = max(0,o[0]-o[2]+1)+max(0, o[1]-o[2]+1)
print("Hinge loss",L_h)
# croos-entropy loss (Softmax)
S = np.exp(o)/np.exp(o).sum()
L_ce= -np.log10(S)
print(L_ce)
print("Cross entorp loss",L_ce[2])

[-2.7   0.86  0.28]
Hinge loss 1.58
[ 1.74703106  0.20094271  0.4528335 ]
Cross entorp loss 0.452833504627


In [ ]:
0.45